ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - com.thanaphoom.ApplicationKt.module

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost/logging-service?user=logging-service&password=1234567890&ssl=false"
  dbFilePath: build/db