ktor:
  development: "$DEVELOPMENT:false"
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - com.thanaphoom.ApplicationKt.module

storage:
  driverClassName: "$DRIVERCLASSNAME:org.postgresql.Driver"
  jdbcURL: "$JDBCURL:jdbc:postgresql://localhost/logging-service?user=logging-service&password=1234567890&ssl=false"